---
dependencies:
  app_lang_selector: ^0.2.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  package_info_plus: ^9.0.0
  riverpod_annotation: ^4.0.0
  riverpod_helper: ^0.2.0
description: A Flutter widget for displaying app information (name, version, build number) and licenses, with Riverpod integration and multi-language support.
dev_dependencies:
  auto_exporter: ^4.1.1
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.0
  very_good_analysis: ^10.3.0
environment:
  flutter: '>=1.17.0'
  sdk: ^3.5.0
flutter:
  assets:
    - assets/localizations/
homepage: https://github.com/normidar/colaxy-pkgs/tree/main/packages/app_info_tile
repository: https://github.com/normidar/colaxy-pkgs/tree/main/packages/app_info_tile
issue_tracker: https://github.com/normidar/colaxy-pkgs/issues
name: app_info_tile
topics:
  - app-info
  - license
  - package-info
  - app
  - easy-localization
version: 0.2.0
resolution: workspace