/// Whether an uploaded image was generated by AI.
///
/// Google Play added this as an attestation the developer makes, not
/// something Google detects. It is optional on every upload; omitting it
/// leaves the image unattested, which is what uploads did before the field
/// existed.
///
/// The API has a third value, `aiGeneratedStateUnspecified`, described in its
/// own discovery document as a catch-all for unrecognised values. It is
/// omitted here because sending it says nothing.
///
/// ## Example
///
/// ```dart
/// await session.images.upload(
///   language: 'ja-JP',
///   imageType: PlayImageType.featureGraphic,
///   file: File('fastlane/metadata/android/featureGraphic.png'),
///   aiGeneratedState: PlayAiGeneratedState.aiGeneratedDeveloperAttested,
/// );
/// ```
enum PlayAiGeneratedState {
  /// The developer attests the image was not generated by AI.
  notAiGenerated('aiGeneratedStateNotAiGenerated'),

  /// The developer attests the image was generated by AI.
  aiGeneratedDeveloperAttested('aiGeneratedStateAiGeneratedDeveloperAttested');

  /// Creates a state with the wire name Google Play uses for it.
  const PlayAiGeneratedState(this.wireName);

  /// The value `androidpublisher` expects in `aiGeneratedState`.
  final String wireName;
}
